-- ============================================================
-- 007_create_study_goals.sql
-- Feature: AI Study Planner - Goals Management
-- Agent Alpha | Project Antigravity
-- ============================================================

-- ============================================================
-- 1. STUDY GOALS TABLE
-- Stores user study goals with AI-generated schedules
-- ============================================================

CREATE TABLE public.study_goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (char_length(title) >= 1 AND char_length(title) <= 100),
    description TEXT CHECK (char_length(description) <= 500),
    target_hours INTEGER NOT NULL CHECK (target_hours > 0 AND target_hours <= 1000),
    completed_minutes INTEGER DEFAULT 0 CHECK (completed_minutes >= 0),
    deadline DATE NOT NULL,
    priority INTEGER CHECK (priority >= 1 AND priority <= 3) DEFAULT 2,
    status TEXT CHECK (status IN ('active', 'completed', 'expired', 'archived')) DEFAULT 'active',
    ai_schedule JSONB,
    ai_schedule_generated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Ensure deadline is in the future on creation
    CONSTRAINT deadline_future CHECK (deadline >= CURRENT_DATE)
);

-- Comments for clarity
COMMENT ON TABLE public.study_goals IS 'User study goals with AI-generated schedules for focus planning';
COMMENT ON COLUMN public.study_goals.target_hours IS 'Total hours user wants to dedicate to this goal';
COMMENT ON COLUMN public.study_goals.completed_minutes IS 'Minutes logged via focus sessions (stored for precision)';
COMMENT ON COLUMN public.study_goals.priority IS '1=High, 2=Medium, 3=Low priority';
COMMENT ON COLUMN public.study_goals.ai_schedule IS 'JSON schedule generated by Groq AI (once per goal)';
COMMENT ON COLUMN public.study_goals.ai_schedule_generated IS 'Prevents multiple AI schedule regenerations';

-- ============================================================
-- 2. ENFORCE MAX 5 ACTIVE GOALS PER USER
-- Using trigger for proper constraint messaging
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_max_active_goals()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    active_count INTEGER;
BEGIN
    -- Only check on INSERT or when status changes to 'active'
    IF TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND NEW.status = 'active' AND OLD.status != 'active') THEN
        SELECT COUNT(*) INTO active_count
        FROM public.study_goals
        WHERE user_id = NEW.user_id AND status = 'active';
        
        IF active_count >= 5 THEN
            RAISE EXCEPTION 'GOAL_LIMIT_REACHED: Maximum 5 active goals allowed per user'
                USING HINT = 'Complete or archive existing goals before creating new ones';
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_max_active_goals
    BEFORE INSERT OR UPDATE ON public.study_goals
    FOR EACH ROW EXECUTE FUNCTION public.check_max_active_goals();

-- ============================================================
-- 3. AUTO-UPDATE TIMESTAMP
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_study_goal_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_update_goal_timestamp
    BEFORE UPDATE ON public.study_goals
    FOR EACH ROW EXECUTE FUNCTION public.update_study_goal_timestamp();

-- ============================================================
-- 4. AUTO-COMPLETE GOAL WHEN HOURS REACHED
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_goal_completion()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Convert completed_minutes to hours and compare
    IF NEW.completed_minutes >= (NEW.target_hours * 60) AND NEW.status = 'active' THEN
        NEW.status = 'completed';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_check_goal_completion
    BEFORE UPDATE ON public.study_goals
    FOR EACH ROW EXECUTE FUNCTION public.check_goal_completion();

-- ============================================================
-- 5. INDEXES FOR PERFORMANCE
-- ============================================================

-- Active goals per user (most common query)
CREATE INDEX idx_study_goals_user_active 
    ON public.study_goals(user_id, created_at DESC) 
    WHERE status = 'active';

-- Goals by deadline for expiry checks
CREATE INDEX idx_study_goals_deadline 
    ON public.study_goals(deadline) 
    WHERE status = 'active';

-- ============================================================
-- 6. RLS POLICIES
-- ============================================================

ALTER TABLE public.study_goals ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can view their own goals
CREATE POLICY "Users can view own goals"
    ON public.study_goals
    FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

-- Policy 2: Users can create their own goals
CREATE POLICY "Users can create own goals"
    ON public.study_goals
    FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

-- Policy 3: Users can update their own goals
CREATE POLICY "Users can update own goals"
    ON public.study_goals
    FOR UPDATE
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- Policy 4: Users can delete (archive) their own goals
CREATE POLICY "Users can delete own goals"
    ON public.study_goals
    FOR DELETE
    TO authenticated
    USING (user_id = auth.uid());

-- ============================================================
-- 7. HELPER FUNCTION: Add focus time to goal
-- Called by focus_service when session ends
-- ============================================================

CREATE OR REPLACE FUNCTION public.add_focus_time_to_goal(
    p_goal_id UUID,
    p_minutes INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.study_goals
    SET completed_minutes = completed_minutes + p_minutes
    WHERE id = p_goal_id;
END;
$$;

-- ============================================================
-- END OF MIGRATION
-- ============================================================
